version: '3'
services:
  proxy:
    build: ./proxy/
    image: svametcalf/jbar-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      HOST_NAME: localhost
    links:
      - db
  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - couchdata:/opt/couchdb/data
  data:
    image: alpine:3.5
    volumes:
      - couchdata:/opt/couchdb/data
    command: "/bin/true"

volumes:
  couchdata:
